#!/usr/bin/zsh
set -xe
# save file descriptors to restore them
# https://serverfault.com/questions/103501/how-can-i-fully-log-all-bash-scripts-actions
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/tmp/startup.log 2>&1

echo $SHELL
echo $PATH
#
# Checks if the process has already started. If not start it, otherwise
# bail silently out.
#
function save_start {
    if [ -z "$(pgrep ${1})" ]; then
        $@ &
    fi
}

xrdb -merge ~/.Xresources
feh -z --bg-fill ~/Pictures/*.jpg

save_start "xautolock" "-detectsleep"
save_start "hamster"
save_start "trayer" "--edge" "top" "--align" "right" "--SetDockType" "true"\
    "--SetPartialStrut" "true" "--expand" "true" "--widthtype" "percent"\
    "--width" "10" "--transparent" "true" "--tint" "0x000000"
save_start "xmobar"
save_start "xautolock"
save_start "gnome-keyring-daemon" "--start"
